### PR TITLE
install parallel

### PR DESCRIPTION
**Pull request by RTann**
The `parallel` command is used by `bats` in https://github.com/stackrox/infra

### CODE REVIEW

**Review by BradLugo — COMMENTED** [review]
Can you add it to `stackrox-ui-test` as well

**Comment by RTann** [comment]
@BradLugo when you asked to add parallel to the UI image was it just for consistency between the images, or did you notice it was needed there, too? If it's nost needed there, then I'll close this in favor of removing parallel from infra's tests

**Comment by BradLugo** [comment]
Just for consistency

**Comment by RTann** [comment]
Closing, as this is no longer needed

**Pull request closed without merging**
